### PR TITLE
Feat: check if the user has granted the permission for camera

### PR DESCRIPTION
**Pull request by ShengHsiang**
Check if the user has granted the permission for camera.

Test on:
- platform: macOs Monteret 12.6
- node version: v16.13.2

### CODE REVIEW

**Comment by fzf404** [comment]
I add this code before last month, but i find this code is not necessary, so i remove them.

**Comment by fzf404** [comment]
Does this software can't use in some mac os version?

**Comment by ShengHsiang** [comment]
Ummm, I'm using a 2018 macbook pro with an intel chip and I download the release dmg file, but it doesn't work properly.
My current macOS version is 12.6

**Comment by fzf404** [comment]
it's work on my m1 macbook pro with macos 12.5 / 13.1
do you try this command `sudo xattr -rd com.apple.quarantine /Applications/Monit.app`
I think it's useful for intel chip macbook

**Comment by ShengHsiang** [comment]
I think it is not the problem of installing software, because in addition to the camera other functions can run normally.

In macOS 10.14 and later, the user must explicitly grant permission for each app to access cameras and microphones. Before your app can use the capture system for the first time, macOS shows an alert asking the user to grant your app access to the camera, as shown below.

To reset the authorization state for camera access, type:
`tccutil reset Camera`
This command resets the access authorization settings for all apps, so other apps will prompt the user again. Use this tool to debug the appearance of your privacy justification strings and their localized versions.

[it's a link](https://developer.apple.com/documentation/avfoundation/capture_setup/requesting_authorization_for_media_capture_on_macos?language=objc)

**Comment by fzf404** [comment]
Ok, I was persuaded by you, thank you.

**Pull request merged**
